apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIP
  clusterIP: 10.100.100.100
  # ip를 설정하지 않으면 생략시 1.96.x.x 범위에서 랜덤으로 할당
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
