apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
#  completions: 5
#  parallelism: 2
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
      - name: centos-container
        image: centos:7
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello World'; sleep 25; echo 'Bye'"
      restartPolicy: Never
# never조건은 실패시 container를 다시 동작시킴
#      restartPolicy: OnFailure
# onfailure의 경우 실패시 container를 다시 동작시킴
#  backoffLimit: 3